name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'
    - name: Install Postgres dependencies
      run: |
        sudo apt-get install libpq-dev
    - name: Set up Postgres
      run: |
        docker run -d --name postgres -e POSTGRES_USER=transition -p 5432:5432 postgres:11
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Set up the test database
      run: |
        RAILS_ENV=test \
        DATABASE_URL=postgres://postgres@transition:5432/transition_test \
        bundle exec rake db:setup
    - name: Run the tests
      run: |
        DATABASE_URL=postgres://postgres@transition:5432/transition_test \
        bundle exec rake
